<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\RicosBetterFileSearch.SharedKernel\RicosBetterFileSearch.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Indexing\RicosBetterFileSearch.Modules.Indexing\RicosBetterFileSearch.Modules.Indexing.csproj" />
    <ProjectReference Include="..\..\Folders\RicosBetterFileSearch.Modules.Folders\RicosBetterFileSearch.Modules.Folders.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
