<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharedKernel\RicosBetterFileSearch.SharedKernel\RicosBetterFileSearch.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\RicosBetterFileSearch.Infrastructure\RicosBetterFileSearch.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Folders\RicosBetterFileSearch.Modules.Folders\RicosBetterFileSearch.Modules.Folders.csproj" />
    <ProjectReference Include="..\..\src\Modules\Indexing\RicosBetterFileSearch.Modules.Indexing\RicosBetterFileSearch.Modules.Indexing.csproj" />
    <ProjectReference Include="..\..\src\Modules\Tags\RicosBetterFileSearch.Modules.Tags\RicosBetterFileSearch.Modules.Tags.csproj" />
    <ProjectReference Include="..\..\src\Modules\Search\RicosBetterFileSearch.Modules.Search\RicosBetterFileSearch.Modules.Search.csproj" />
    <ProjectReference Include="..\..\src\Modules\Statistics\RicosBetterFileSearch.Modules.Statistics\RicosBetterFileSearch.Modules.Statistics.csproj" />
  </ItemGroup>

</Project>